### PR TITLE
Added Docker chapter to Redme

### PR DESCRIPTION
**Pull request by tinooo**
Basic guide for new users to getting a serial sensor in NodeRed on their NAS

Since I've struggled a lot in the beginning with limited experience in linux systems to getting everything running in NodeRed, I thought about contributing and helping new users.

A lot of German users will need this driver for getting a smartmeter node running in NodeRed. There are many forums entries linking to this repo, but without explicite guide or help. I was thinking to add some basic step by step guide to get them started. This would have helped me a lot a year ago.

Hop you consider merging this. Let me know if you want me to change some parts or feel free to do it yourself!

### CODE REVIEW

**Comment by robertklep** [comment]
Thank you for your effort 😊

Is it possible to rewrite it to make it more generic? Because most of what you are writing applies to other Dockerized apps too (like zigbee2mqtt, Home Assistant, etc), and should also apply to Docker containers created using DSM's UI.

**Comment by tinooo** [comment]
Yes that is true. However, I've focused it in NodeRed, since that's the only environment I've running and tested here.

But you're corret it should work similar for other dockerized stuff. I've pushed some changes, adapting it slightly to make it a little more generic. 
But it is still focused on NodeRed, since my knowledge on docker in general is limited and I don't want to bring up incorrect information here.

**Comment by robertklep** [comment]
No problem, if you don't mind I'll rewrite what you wrote before I push it to the repo.

**Comment by robertklep** [comment]
I've updated the documentation based on your text 😅 I'll close this PR since I didn't use it.

**Comment by tinooo** [comment]
much appreciated! Hope this will help some people.

**Pull request closed without merging**
